---
title: "Grafos 1"
author: "Javier Cano Montero"
date: "27 de febrero de 2017"
output: html_document
---

```{r setup, include=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(igraph)
```

```{r 1}
df <- read.table("/home/javier/practica_1_grafos/data/out.ego-twitter")
g <- graph_from_data_frame(df)
rm(df)
```


```{r 2}
V(g)$size <- 8
V(g)$frame.color <- "white"
V(g)$color <- "orange"
V(g)$label <- "" 
E(g)$arrow.mode <- 1
plot(g)
```

```{r 3}
hist(degree(g))
summary(degree(g))
```

```{r 4}
sg <- induced_subgraph(g, V(g)[which(V(g)$name %in% c("190","191","192","193","194","13167"))])
plot(sg)
```
No es fuertemente conexo
```{r 5}
# Max followers
which.max(degree(g, mode="in"))
# Max following
which.max(degree(g, mode="out"))
```

```{r 6a}
adjacent_vertices(g,V(g)[V(g)$name=="1305"],mode="in")
```


```{r 7}
adjacent_vertices(g,V(g)[V(g)$name=="1373"],mode="out")
```

```{r 8}
id <- V(g)[V(g)$name=="13815"]
length(adjacent_vertices(g,id,mode="in")[[1]])/length(adjacent_vertices(g,id,mode="out")[[1]])
```

```{r 9}
is.connected(g)

cl <- cluster_infomap(g)
print(sizes(cl))
```

```{r 10}
id_com <- which(sizes(cl)==35)
sg <- induced_subgraph(g,V(g)[cl$membership==id_com])
degree(sg)
plot(sg)
```

```{r 11a}
id_max <- which.max(sizes(cl))
sg <- induced_subgraph(g,V(g)[cl$membership==id_max])
which.max(closeness(sg))
```

```{r 11b}
which.max(betweenness(sg))
```
